[project]
name = "Xtract"
version = "1.1.0"
description = "Simple extraction tool for X4 Foundations CAT files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "rich>=14.1.0",
]
